Repository GrupaMedialnaSalwator/kompas.sds, pull requests merged in 2022-03, with the labels that each got.

#63 Map icons change
  lib/model/mapDatabase.dart
  pubspec.lock
Labels: feature

#62 Info screen refurb
  lib/statics/kompasText.dart
  lib/widgets/achievementTracker_widget.dart
  lib/widgets/infoView_widget.dart
  pubspec.lock
  pubspec.yaml
Labels: feature

#79 Add labirynt
  assets/images/trip03/trip03_mapa.jpg
  lib/controller/tripData_controller.dart
  lib/main.dart
  lib/model/tripDatabase.dart
  lib/widgets/tripViewStepButtons_widget.dart
  lib/widgets/tripViewStepSwitch_widget.dart
  pubspec.lock
  pubspec.yaml
Labels: feature

#80 Build setup
  README.md
  android/app/build.gradle
  lib/main.dart
  lib/widgets/mapView_widget.dart
  lib/widgets/selectTrip_widget.dart
Labels: workflow

#90 Alfa varia
  assets/images/trip03/trip03_mapa.jpg
  assets/images/trip03/trip03_mapa.png
  lib/model/tripDatabase.dart
  lib/view/mapCard_screen.dart
  lib/widgets/mapCardHero_widget.dart
  lib/widgets/mapPoint_widget.dart
  pubspec.yaml
Labels: feature

#92 fix manifest for release
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/profile/AndroidManifest.xml
Labels: bug
